FROM node:20-slim

WORKDIR /app

ENV NODE_ENV=production
ENV STEAM_DATA_DIR=/data/SteamData

COPY package*.json ./
RUN npm install --omit=dev

COPY index.js ./

RUN mkdir -p /data

CMD ["npm", "start"]